#version: '3.1'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=LahmannDatabase
    volumes: 
      - /home/rip/Projects/test/db:/var/lib/mysql
      - /home/rip/Projects/backup:/backup
